---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ resourcegroup_name }}"
    location: "{{ resourcegroup_location }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ virtualnetwork_name }}"
    address_prefixes: "{{ vn_address_prefixes }}"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ subnet_name }}"
    virtual_network: "{{ virtualnetwork_name }}"
    address_prefix: "{{ subnet_address_prefixes }}"

- name: Create public IP address for loadbalancer
  azure_rm_publicipaddress:
    resource_group: "{{ resourcegroup_name }}"
    allocation_method: Static
    name: "{{publicIP}}"
    domain_name: "{{ domain_name }}"

- name: Create a network interface for loadbalancer
  azure_rm_networkinterface:
    name: loadbalancer-nic
    resource_group: "{{ resourcegroup_name }}"
    virtual_network: "{{ virtualnetwork_name }}"
    subnet_name: "{{subnet_name}}"
    security_group: "{{securitygroup_name}}"
    public_ip_name: "{{publicIP}}"

- name: Create loadbalancer Virtual Machine
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ item.name }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    open_ports: "{{ item.ports }}"
    network_interface_names: "loadbalancer-nic"
    ssh_public_keys:
    - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
      key_data: "{{ ssh_private_key_path }}"
    vm_size: "{{ vm_size }}"
    tags:
      site: "{{ item.site | default(None) }}"
      role: "{{ item.role | default(None)}}"
    image:
      offer: "{{ offer }}"
      publisher: "{{ publisher }}"
      sku: "{{ sku }}"
      version: "{{ image_version }}"
  loop: "{{ loadbalancer_creation }}"

- name: Create VM's for database, datagrid and rhsso.
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ item.name }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    ssh_public_keys:
    - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
      key_data: "{{ ssh_private_key_path }}"
    vm_size: "{{ vm_size }}"
    tags:
      site: "{{ item.site | default(None) }}"
      role: "{{ item.role | default(None)}}"
    image:
      offer: "{{ offer }}"
      publisher: "{{ publisher }}"
      sku: "{{ sku }}"
      version: "{{ image_version }}"
  loop: "{{ vm_creation_list }}"
