---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ resourcegroup_name }}"
    location: "{{ resourcegroup_location }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ virtualnetwork_name }}"
    address_prefixes: "{{ vn_address_prefixes }}"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ subnet_name }}"
    virtual_network: "{{ virtualnetwork_name }}"
    address_prefix: "{{ subnet_address_prefixes }}"

- name: Create security groups
  azure_rm_securitygroup:
  rules:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ item.name }}"
      protocol: "{{ item.protocol }}"
      destination_port_range: "{{ item.destination_port_range }}"
      priority: "{{ item.priority }}"
  loop: "{{ nsg }}"

- name: Create a network interface
  azure_rm_networkinterface:
    name: "{{ item.name }}"
    resource_group: "{{ resourcegroup_name }}"
    virtual_network: "{{ virtualnetwork_name }}"
    subnet_name: "{{subnet_name}}"
    security_group: "{{ item.role }}"
    ip_configurations:
      - name: "{{ item.name }}"
        public_ip_address_name: "{{ item.name }}-ip"
        primary: True
  loop: "{{ vm }}"

- name: Create Virtual Machine
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ item.name }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    network_interface_names: "{{ item.role }}"
    ssh_public_keys:
    - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
      key_data: "{{ ssh_key_path }}"
    vm_size: "{{ vm_size }}"
    tags:
      site: "{{ item.site | default(None) }}"
      role: "{{ item.role | default(None)}}"
    image:
      offer: "{{ offer }}"
      publisher: "{{ publisher }}"
      sku: "{{ sku }}"
      version: "{{ image_version }}"
  loop: "{{ vm }}"
