---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ resourcegroup_name }}"
    location: "{{ resourcegroup_location }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ virtualnetwork_name }}"
    address_prefixes: "10.0.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ subnet_name }}"
    virtual_network: "{{ virtualnetwork_name }}"
    address_prefix: "10.0.1.0/24"

- name: Create Network Security Group that allows HTTP
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ securitygroup_name }}"
    rules:
    - name: HTTP
      protocol: "{{ item.protocol }}"
      destination_port_range: " {{ item.destination_port_range }}"
      access: Allow
      priority: "{{ item.priority }}"
      direction: Inbound
  with_items:
      - { protocol: Tcp, destination_port_range: 80, priority: 100 }
      - { protocol: Tcp, destination_port_range: 443, priority: 120 }

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ item.name }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    ssh_password_enabled: false
    ssh_public_keys:
    - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
      key_data: "{{ lookup('file', '/home/{{ local_user }}/.ssh/ansible-middleware-core.pub') }}"
    vm_size: " {{ vm_size }}"
    tags:
      site: "{{ item.site }}"
      role: "{{ item.role }}"
    image:
      offer: "{{ offer }}"
      publisher: "{{ publisher }}"
      sku: "{{ sku }}"
      version: latest
  with_items:
      - { name: 'loadbalancer0', site: 'site0', role: 'loadbalancer' }
      - { name: 'site1-datagrid1', site: 'site1', role: 'datagrid' }
      - { name: 'site1-datagrid2', site: 'site1', role: 'datagrid' }
      - { name: 'site2-datagrid1', site: 'site2', role: 'datagrid' }
      - { name: 'site2-datagrid2', site: 'site2', role: 'datagrid' }
      - { name: 'site1-rhsso1', site: 'site1', role: 'rhsso' }
      - { name: 'site1-rhsso2', site: 'site1', role: 'rhsso' }
      - { name: 'site2-rhsso1', site: 'site2', role: 'rhsso' }
      - { name: 'site2-rhsso2', site: 'site2', role: 'rhsso' }
      - { name: 'site1-database1', site: 'site1', role: 'database' }
      - { name: 'site1-database2', site: 'site1', role: 'database' }
      - { name: 'site2-database1', site: 'site2', role: 'database' }


