---
- name: Remove a VM and all resources that were autocreated
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup_name }}"
    name: "{{ item }}"
    remove_on_absent: all_autocreated
    state: absent
  loop: "{{ vm_names }}"
