- name: Refresh inventory and roles git repo
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    repo_url: "https://github.com/ansible-middleware/cross-dc-rhsso-demo.git"
    branch: aws
    rhn_username: foo
    rhn_password: bar
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ playbook_dir }}/cross-dc-rhsso-demo"
        version: "{{ branch }}"
        depth: 1
        single_branch: yes
        clone: yes
        update: yes

- import_playbook: cross-dc-rhsso-demo/playbooks/all.yml
  vars:
    tls_certs_lookup_path: "../../files/"
