- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resourcegroup_name: ansible-middileware-rg
    virtualnetwork_name: ansible-middileware-vn
    subnet_name: ansible-middileware-subnet
    securitygroup_name: ansible-middileware-sg
    publicIP: ansible-middileware-ip
    public_ip_address_name: ansible-middileware-public-ip
    resourcegroup_location: eastus
    admin_username: azureuser 
    admin_password: Password12345
    location: eastus
    key_data:
    offer: RHEL
    publisher: RedHat
    sku: 8-LVM
    vm_size: "Standard_D2s_v3"
    domain_name: "rhsso"
    local_user: hcheruku
    ssh_private_key_path: '/home/hcheruku/.ssh/1643057028_7780352.pub'
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resourcegroup_name }}"
        location: "{{ resourcegroup_location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resourcegroup_name }}"
        name: "{{ virtualnetwork_name }}"
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resourcegroup_name }}"
        name: "{{ subnet_name }}"
        virtual_network: "{{ virtualnetwork_name }}"
        address_prefix: "10.0.1.0/24"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resourcegroup_name }}"
        allocation_method: Static
        name: "{{publicIP}}"
        domain_name: "{{ domain_name }}"

    - name: Create a network interface with private IP address only (no Public IP)
      azure_rm_networkinterface:
        name: loadbalancer-nic
        resource_group: "{{ resourcegroup_name }}"
        virtual_network: "{{ virtualnetwork_name }}"
        subnet_name: "{{subnet_name}}"
        security_group: "{{securitygroup_name}}"
        public_ip_name: "{{publicIP}}"

    - name: Create loadbalancer VM
      azure_rm_virtualmachine:
        resource_group: "{{ resourcegroup_name }}"
        name: "{{ item.name }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        open_ports: "{{ item.ports }}"
        network_interface_names: "loadbalancer-nic"
        ssh_public_keys:
        - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
          key_data: "{{ ssh_private_key_path }}"
        vm_size: "{{ vm_size }}"
        tags:
          site: "{{ item.site | default(None) }}"
          role: "{{ item.role | default(None)}}"
        image:
          offer: "{{ offer }}"
          publisher: "{{ publisher }}"
          sku: "{{ sku }}"
          version: latest
      with_items:
          - { name: 'test', site: 'test', role: 'test', ports: ['443','22']}
    
    - name: Create other VM's
      azure_rm_virtualmachine:
        resource_group: "{{ resourcegroup_name }}"
        name: "{{ item.name }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        ssh_public_keys:
        - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
          key_data: "{{ lookup('file', '/home/{{ local_user }}/.ssh/1643057028_7780352.pub') }}"
        vm_size: "{{ vm_size }}"
        tags:
          site: "{{ item.site | default(None) }}"
          role: "{{ item.role | default(None)}}"
        image:
          offer: "{{ offer }}"
          publisher: "{{ publisher }}"
          sku: "{{ sku }}"
          version: latest
      with_items:
          - { name: 'test1', site: 'test', role: 'test'}