- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resourcegroup_name: ansible-middileware-rg
    virtualnetwork_name: ansible-middileware-vn
    subnet_name: ansible-middileware-subnet
    securitygroup_name: ansible-middileware-sg
    publicIP: ansible-middileware-ip
    resourcegroup_location: eastus
    admin_username: azureuser 
    admin_password: Password12345
    location: eastus
    key_data:
    offer: RHEL
    publisher: RedHat
    sku: 8-LVM
    vm_size: "Standard_D2s_v3"
    local_user: hcheruku
  tasks:
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resourcegroup_name }}"
        allocation_method: Static
        name: "{{publicIP}}"
        domain_name: test1234

    - name: Create a network interface with private IP address only (no Public IP)
      azure_rm_networkinterface:
        name: ansible-middileware-nic
        resource_group: "{{ resourcegroup_name }}"
        virtual_network: "{{ virtualnetwork_name }}"
        subnet_name: "{{subnet_name}}"
        security_group: "{{securitygroup_name}}"
        public_ip_name: "{{publicIP}}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resourcegroup_name }}"
        name: "{{ item.name }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        open_ports: "{{ item.ports }}"
        public_ip_allocation_method: Disabled
        network_interface_names: "ansible-middileware-nic"
        ssh_public_keys:
        - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
          key_data: "{{ lookup('file', '/home/{{ local_user }}/.ssh/1643057028_7780352.pub') }}"
        vm_size: "{{ vm_size }}"
        tags:
          site: "{{ item.site | default(None) }}"
          role: "{{ item.role | default(None)}}"
        image:
          offer: "{{ offer }}"
          publisher: "{{ publisher }}"
          sku: "{{ sku }}"
          version: latest
      with_items:
          - { name: 'test', site: 'test', role: 'test', ports: '443'}
          - { name: 'test1', site: 'test', role: 'test', ports: '443'}
