---
- name: "Query for existing running instances"
  ec2_instance_info:
    region: "{{ item }}"
    filters:
      "tag:Environment": crossdc-rhsso-demo
      instance-state-name: [ "running", "pending" ]
  register: instances
  loop: "{{ vpc | list }}"

- debug:
    msg: "{{ instances | community.general.json_query(querystr) | flatten }}"
  loop: "{{ vpc | list }}"
  vars:
    querystr: "results[*].instances[?contains(placement.availability_zone, '{{ item }}')].instance_id"

- name: "Terminate EC2 instances"
  ec2_instance:
    region: "{{ item }}"
    instance_ids: "{{ instances | community.general.json_query(querystr) | flatten }}"
    state: absent
  retries: 3
  delay: 5
  loop: "{{ vpc | list }}"
  vars:
    querystr: "results[*].instances[?contains(placement.availability_zone, '{{ item }}')].instance_id"
