---
resourcegroup_name: ansible-middileware-rg
virtualnetwork_name: ansible-middileware-vn
subnet_name: ansible-middileware-subnet
securitygroup_name: ansible-middileware-sg
resourcegroup_location: eastus
admin_username: azureuser 
admin_password: Password12345
location: eastus
key_data:
offer: RHEL
publisher: RedHat
sku: 8-LVM
vm_size: "Standard_D2s_v3"